version: '3.3'

services:

  zookeeper:
    image: library/zookeeper:3.4.13
    restart: always
    environment: 
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    restart: always
    environment: 
      KAFKA_BROKER_ID: 1 
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "logging:20:1,notifications:10:1,invoicing:10:1,orders:10:1" 
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092"
    ports: 
      - 9092:9092
    depends_on: 
      - zookeeper
  
  ordermanager:
    image: unict/ordermanager:1.0.0
    restart: always
    environment:
      appVersion: 1.0.0 
      spring_data_mongodb_host: mongodb
      spring_data_mongodb_port: 27017
      spring_data_mongodb_database: orders
      spring_kafka_bootstrap-servers: "${BOOTSTRAP_SERVERS}"
      kafkaMainTopic: orders
      kafkaNotificationTopic: notifications
      kafkaInvoicingTopic: invoicing
      kafkaLogTopic: logging
      heartbeatHost: "${HEARTBEAT_HOST}"
      heartbeatPort: "${HEARTBEAT_PORT}"
      heartbeatBasePath: "${HEARTBEAT_PATH}"
      heartbeatPeriod: "${HEARTBEAT_PERIOD}"
    ports:
      - 9080:9080
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:4.2
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  
volumes: 
  mongodb_data: